[package]
name = "tokio_getting_started_video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
simple_logger = "4.3.0"
tokio = { version = "1.35.0", features = ["full"] }